version: '3.4'
services:

  # Collector
  
  otel-collector:
    image: otel/opentelemetry-collector-contrib
    volumes:
      - /Users/nguggil/Desktop/otel-browser-metrics/otel_config.yml:/etc/otel-config.yaml
    command: ["--config=/etc/otel-config.yaml"]
    #volumes:
     # - ./otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml
    ports:
      - 8888:8888 # Prometheus metrics exposed by the Collector
      - 9123:9123 # Prometheus exporter metrics
      - 4317:4317 # OTLP gRPC receiver
      - 4318:4318 # OTLP http receiver
    

