receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
        cors:
          allowed_origins:
            - http://*
            - https://*

exporters:
  debug:
    verbosity: detailed

service:
  pipelines:
    metrics:
      receivers: [otlp]
      exporters: [debug]



      

#exporters:
  #console:
   # logLevel: debug
  #otlp:
   # endpoint: "0.0.0.0:4318"
  #prometheus:
   # endpoint: "0.0.0.0:9123"

#service:
  #pipelines:
   # metrics:
    #  receivers: [otlp]
     # exporters: [console]
    
