global:
  scrape_interval: 15s  # Default scrape interval

scrape_configs:
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['localhost:8888']  # Prometheus exporter exposed by OTel collector
